# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713f1a50eeee18fef6337d6278415a56d7021f735cc4c5ef89da38dbb8ddc3a728f32d72726cc6901d57681eb6cc07602ed46290bf395bdcc99de50da2d8c403

test:
  secret_key_base: c3fa2e75a123e7711f790d3cf7f560225387f3ef3aad47bf27610ba72c0db2d241c3ac2b42a02791f2602cda3466825b099f8a400e9dad0dcb49ea9b8b1d0ca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
